# Generated by Django 2.0.5 on 2018-05-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacePlay', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
