# Generated by Django 2.0.5 on 2018-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePlay', '0003_auto_20180503_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face',
            field=models.ImageField(default=2, upload_to=models.CharField(max_length=30)),
            preserve_default=False,
        ),
    ]
