# Generated by Django 2.0.5 on 2018-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePlay', '0004_user_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.ImageField(upload_to=''),
        ),
    ]
