# Generated by Django 2.0.5 on 2018-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePlay', '0005_auto_20180506_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face',
            field=models.CharField(help_text='存放人脸图片的路径', max_length=100),
        ),
    ]
