# Generated by Django 2.0.5 on 2018-05-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePlay', '0006_auto_20180506_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(default=None, help_text='存放用户图像风格转换的路径', max_length=100),
            preserve_default=False,
        ),
    ]
