# Generated by Django 2.0.5 on 2018-05-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePlay', '0007_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='C_S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=12)),
                ('c_name', models.CharField(max_length=20)),
                ('c_time', models.CharField(max_length=20)),
                ('c_room', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=12)),
                ('s_name', models.CharField(max_length=10)),
                ('s_face', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=12)),
                ('t_name', models.CharField(max_length=10)),
                ('t_face', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='c_s',
            name='c_id',
            field=models.ForeignKey(on_delete=True, to='FacePlay.Course'),
        ),
    ]
